on: 
  push:

jobs:
  build:
    runs-on: debian-latest
    steps:
      - run: apt install nix
      - run: nix develop  --experimental-features 'nix-command flakes'
      - run: make
      - run: make clean
      - run: make test
