on: [push]
  jobs:
    build:
      runs-on: debian-latest
      steps:
        - apt install nix
        - nix develop  --experimental-features 'nix-command flakes'
        - make
        - make clean
        - make test
