on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install nix
      - run: cat flake.nix
      - run: sudo nix develop  --experimental-features 'nix-command flakes'
      - run: make
      - run: make clean
      - run: make test
